{{- if or .Values.kafka.enabled .Values.connect.enabled }}
{{- if or .Values.kafka.hpa.enabled .Values.connect.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kafka-kraft-on-k8s.fullname" . }}
  labels:
    {{- include "kafka-kraft-on-k8s.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kafka-kraft-on-k8s.fullname" . }}
  minReplicas: {{ or .Values.kafka.autoscaling.minReplicas .Values.connect.autoscaling.minReplicas }}
  maxReplicas: {{ or .Values.kafka.autoscaling.maxReplicas .Values.connect.autoscaling.maxReplicas }}
  metrics:
    {{- if or .Values.kafka.autoscaling.targetCPUUtilizationPercentage .Values.connect.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ or .Values.autoscaling.targetCPUUtilizationPercentage .Values.connect.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if or .Values.autoscaling.targetMemoryUtilizationPercentage .Values.connect.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ or .Values.autoscaling.targetMemoryUtilizationPercentage .Values.connect.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
