{{- if or .Values.kafka.ingress.enabled .Values.connect.ingress.enabled -}}
{{- $fullName := include "kafka-kraft-on-k8s.fullname" . -}}
{{- $svcPort := or .Values.kafka.service.port .Values.connect.service.port -}}
{{- if and (or .Values.kafka.ingress.className .Values.connect.ingress.className) (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey (or .Values.kafka.ingress.annotations .Values.connect.ingress.annotations) "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.kafka.ingress.annotations "kubernetes.io/ingress.class" .Values.kafka.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kafka-kraft-on-k8s.labels" . | nindent 4 }}
  {{- with or .Values.kafka.ingress.annotations .Values.connect.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if or (and .Values.kafka.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) (and .Values.connect.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  ingressClassName: {{ or .Values.kafka.ingress.className .Values.connect.ingress.className }}
  {{- end }}
  {{- if or .Values.kafka.ingress.tls .Values.connect.ingress.tls }}
  tls:
    {{- range or .Values.kafka.ingress.tls .Values.connect.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range or .Values.kafka.ingress.hosts .Values.connect.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
