{{- if .Values.connect.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.connect.service.name }}
  labels:
    {{- toYaml .Values.connect.service.labels | nindent 4 }}
  annotations:
    {{- toYaml .Values.connect.service.annotations | nindent 4 }}
  namespace: {{ .Values.connect.namespace }}
spec:
  type: {{ .Values.connect.service.type }}
  ports:
    {{- range $index, $port := .Values.connect.ports }}
    - port: {{ .port }}
      name: {{ .name | quote }}
      protocol: TCP
      targetPort: {{ .port }}
      {{- end }}
  selector:
    {{- toYaml .Values.connect.service.selector | nindent 4 }}
{{- end }}
