{{- if .Values.kafka.enabled }}
{{- if .Values.kafka.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kafka.serviceAccount.name }}
  {{- with .Values.kafka.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kafka.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.kafka.serviceAccount.automount }}
{{- end }}
{{- end }}
