{{- if .Values.connect.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.connect.namespace }}
  name: {{ .Values.connect.rbac.name }}
rules:
  {{- with .Values.connect.rbac.apiGroups }}
  - apiGroups:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- with .Values.connect.rbac.resources }}
    resources:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.connect.rbac.verbs }}
    verbs:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
